# Generated by Django 4.1.2 on 2022-10-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_cost_remove_product_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('cost', models.IntegerField(verbose_name='Вартість')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Додаткові опції',
                'verbose_name_plural': 'Додаткові опції',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-datetime_create',), 'verbose_name': 'Товари', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productsubtype',
            options={'verbose_name': 'Вид товару', 'verbose_name_plural': 'Вид товару'},
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='extra_cost1',
            field=models.IntegerField(default=0, verbose_name='Додатково 1 Ціна'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='extra_cost2',
            field=models.IntegerField(default=0, verbose_name='Додатково 2 Ціна'),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='extra1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 1'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='extra2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 2'),
        ),
    ]
