# Generated by Django 4.1.2 on 2022-10-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productextra_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtype',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='productsubtype',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='productsubtype',
            name='extra_cost1',
        ),
        migrations.RemoveField(
            model_name='productsubtype',
            name='extra_cost2',
        ),
        migrations.AddField(
            model_name='product',
            name='extra1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_cost1',
            field=models.IntegerField(default=0, verbose_name='Додатково 1 Ціна'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_cost2',
            field=models.IntegerField(default=0, verbose_name='Додатково 2 Ціна'),
        ),
    ]
