# Generated by Django 4.1.2 on 2022-10-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productsubtype_extra1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_cost1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_cost2',
        ),
        migrations.AddField(
            model_name='product',
            name='extra3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 3'),
        ),
    ]
