# Generated by Django 4.1.2 on 2022-10-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_extra_cost1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.productextra', verbose_name='Додатково 3'),
        ),
    ]
