# Generated by Django 4.1.2 on 2022-10-10 19:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('about', models.CharField(max_length=200, verbose_name='Опис')),
                ('image', models.ImageField(upload_to=home.models.Banner.get_file_name, verbose_name='Зображення')),
                ('button', models.CharField(default='', max_length=50, verbose_name='Текст, кнопка')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
                'ordering': ('access', 'title'),
            },
        ),
    ]
