# Generated by Django 4.1.2 on 2022-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
