# Generated by Django 4.1.2 on 2022-10-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('date_create', 'title'), 'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
    ]
