# Generated by Django 4.1.2 on 2022-10-21 12:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_banner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('about', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to=home.models.Title_main.get_file_name, verbose_name='Зображення')),
                ('button_title', models.CharField(max_length=20, verbose_name='Кнопка назва')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовок',
            },
        ),
    ]
