# Generated by Django 4.1.2 on 2022-10-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureinfo',
            name='about_left',
            field=models.TextField(verbose_name='Опис зліва <br>'),
        ),
        migrations.AlterField(
            model_name='featureinfo',
            name='about_right',
            field=models.TextField(verbose_name='Опис справа <br>'),
        ),
    ]
