# Generated by Django 4.1.2 on 2022-10-21 12:33

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_featureinfo_about_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('about', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to=about.models.Title.get_file_name, verbose_name='Зображення')),
                ('video', models.FileField(upload_to=about.models.Title.get_file_name, verbose_name='Відео')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовок',
            },
        ),
    ]
