# Generated by Django 4.1.2 on 2022-10-21 12:41

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='video',
            field=models.ImageField(upload_to=about.models.Title.get_file_name, verbose_name='Відео'),
        ),
    ]
