# Generated by Django 4.1.2 on 2022-10-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_title_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='video',
            field=models.CharField(max_length=200, verbose_name='Посилання на відео'),
        ),
    ]
