# Generated by Django 4.1.2 on 2022-10-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_title_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='video',
        ),
    ]
