# Generated by Django 4.1.2 on 2022-10-19 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('order', models.SmallIntegerField(unique=True, verbose_name='Порядок')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_uuid', models.UUIDField(default=uuid.UUID('b1492caf-72af-4ca8-bdc2-587f341d3ff2'), verbose_name='Код заказу')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=13, verbose_name="Ім'я")),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('address', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('post_code', models.CharField(max_length=5)),
                ('commentary', models.TextField(blank=True, verbose_name='Коментарій')),
                ('order', models.TextField(blank=True, default='', verbose_name='Замовлення')),
                ('status', models.CharField(blank=True, choices=[('open', 'На огляді'), ('verify', 'Перевірений'), ('sent', 'Відправлено'), ('completed', 'Завершено')], default='open', max_length=10, verbose_name='Статус замовлення')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата і час оновлення')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.posttype', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('time_update', 'time_create'),
            },
        ),
    ]
