# Generated by Django 4.1.2 on 2022-10-19 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='person_uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('7272146b-9e16-4c86-b730-b54b9cd38769'), verbose_name='Код заказу'),
        ),
    ]
