# Generated by Django 4.1.2 on 2022-10-19 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_person_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='person_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, verbose_name='Код заказу'),
        ),
    ]
