# Generated by Django 4.1.2 on 2022-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_number',
            field=models.CharField(max_length=5, null=True, verbose_name='Відділення'),
        ),
    ]
